#服务端口
server:
  port: 61001
#本项目名称
spring:
  application:
    name: sboot_service_user
#数据库相关配置
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/ee17?characterEnconding=utf-8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 5 #初始化连接个数
      min-idle: 5 #最小空闲连接数
      max-active: 20 #最大连接活跃数
      max-wait: 10000 #最长等待时间
      test-on-borrow: true #申请连接时检测连接是否有效
      test-on-return: false #归还连接时检测连接是否有效
      time-between-eviction-runs-millis: 60000 #检测连接是否有效间隔时间
      min-evictable-idle-time-millis: 300000 #连接在连接池中最小生存时间
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wenliang.demo.entity
  type-handlers-package:
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: false
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    capital-mode: false
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义SQL注入器
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false
    #配置JdbcTypeForNull
    jdbc-type-for-null: 'null'
